spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022212952?createDatabaseIfNotExist=true'
    username: 2022212952
    password: 2022212952
  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    org:
      example: debug
  pattern:
    console: '%d{yyyy-mm-dd HH:mm:ss} %-5level %C.%M[%line] - %msg%n'
    file: '%d{yyyy-mm-dd HH:mm:ss} %-5level %C.%M[%line] - %msg%n'
  file:
    path: D:/applicationlog/application.log

